library firebase_remote_config_hybrid;

import 'package:firebase_remote_config_hybrid_platform_interface/firebase_remote_config_hybrid_platform_interface.dart';

part 'src/firebase_remote_config_hybrid.dart';
